from ViennaRNA import RNA


def ss_predict(seq, temperature=37):
    md = RNA.md()
    md.temperature = temperature
    fc = RNA.fold_compound(seq, md)
    ss, mfe = fc.mfe()
    return ss, mfe


def bbp_predict(seq, temperature=37):
    md = RNA.md()
    md.temperature = temperature
    fc = RNA.fold_compound(seq, md)
    fc.pf()
    bpp = fc.bpp()
    return bpp


def sub_predict(seq, temperature=37, delta=3, max_structures=10):
    md = RNA.md()
    md.temperature = temperature
    fc = RNA.fold_compound(seq, md)
    structures = []
    for sub in fc.subopt(delta):
        structures.append(sub.structure)
        if len(structures) >= max_structures:
            break
    return structures

# seq = "AGACGACAAGGUUGAAUCGCACCCACAGUCUAUGAGUCGGUG"

# print(ss_predict(seq, 37))
# print(bbp_predict(seq, 37)[7][14])
# print(sub_predict(seq, 37))
# for i, result in enumerate(sub_predict(seq, 100)):
#     print(i)
#     print(result)

sol=sub_predict("GAUCAUGAGCGGCUACGUUAACAACCCCGAGGCUACAAACGCUCUCAUCGACAAGGACGGCUGGCUGCACAGCGGCGACAUCGCCUACUGGGACGAGGACGAGCACUUCUUCAUCGUGGACCGGCUGAAGAGCCUGAUCAAAUACAAGGGCUACCAGGUAGCCCCAGCCGAACUGGAGAGCAUCCUGCUGCAACACCCCAACAUCUUCGACGCCGGGGUCGCCGGCCUGCCCGACGACGAUGCCGGCGAGCUGCCCGCCGCAGUCGUCGUGCUGGAACACGGUAAAACCAUGACCGAGAAGGAGAUCGUGGACUAUGUGGCCAGCCAGGUUACAACCGCCAAGAAGCUGCGCGGUGGUGUUGUGUUCGUGGACGAGGUGCCUAAAGGACUGACCGGCAAGUUGGACGCCCGCAAGAUCCGCGAGAUUCUCAUUAAGGCCAAGAAGGGCGGCAAGAUCGCCGUGUAAGCUGGAGCCUCGGUGGCCUACAGUGCUAGAGGAGGUCAGAAGAGGGCAUUGGAUCCCCCAGAACUGGAGUUAUACGGUAACCUCGUGGUGGUGCGCAGCCACCAUGUGGAUGGAUAUUGAGUUCCAAACACUGGUCCUGUGCAAGAGCAUCCAGUGCUCUUAAGUGCUGAGCCAUCUCUUUAGCUCCGCUUCUUGCCCCUUGGGCCUCCCCCCAGCCCCUCCUCCCCUUCCUGCACCCGUACCCCCGUGGUCUUUGAAUAAAGUCUGAGUGGGCGGCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGCAUAUGACUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",10)

