import csv
import sys
import os


def preprocess(cds, utr_upstream, insert, utr_downstream, name=None, outpath='data.csv'):
    upstream = cds + utr_upstream
    seq = upstream + insert + utr_downstream

    current_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(current_dir)
    sys.path.append(project_root)

    if name is None:
        if os.path.exists(outpath) and os.path.getsize(outpath) > 0:
            with open(outpath, "r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                if reader.fieldnames:
                    reader.fieldnames = [name.strip() for name in reader.fieldnames]
                rows = list(reader)
                if rows:
                    last_row = rows[-1]
                    last_idx = last_row.get('idx', '').strip()
                    if last_idx.isdigit():
                        name = str(int(last_idx) + 1)
                    else:
                        name = '1'
                else:
                    name = '1'
        else:
            name = '1'

    new_row = [name, contact, len(upstream), len(upstream) + len(insert) - 1]

    with open(outpath, "a", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(new_row)


cds = 'GGGAAAUAAGAGAGAAAAGAAGAGUAAGAAGAAAUAUAAGACCCCGGCGCCGCCACCAUGGAAGAUGCCAAAAACAUUAAGAAGGGCCCAGCGCCAUUCUACCCACUCGAAGACGGGACCGCCGGCGAGCAGCUGCACAAAGCCAUGAAGCGCUACGCCCUGGUGCCCGGCACCAUCGCCUUUACCGACGCACAUAUCGAGGUGGACAUUACCUACGCCGAGUACUUCGAGAUGAGCGUUCGGCUGGCAGAAGCUAUGAAGCGCUAUGGGCUGAAUACAAACCAUCGGAUCGUGGUGUGCAGCGAGAAUAGCUUGCAGUUCUUCAUGCCCGUGUUGGGUGCCCUGUUCAUCGGUGUGGCUGUGGCCCCAGCUAACGACAUCUACAACGAGCGCGAGCUGCUGAACAGCAUGGGCAUCAGCCAGCCCACCGUCGUAUUCGUGAGCAAGAAAGGGCUGCAAAAGAUCCUCAACGUGCAAAAGAAGCUACCGAUCAUACAAAAGAUCAUCAUCAUGGAUAGCAAGACCGACUACCAGGGCUUCCAAAGCAUGUACACCUUCGUGACUUCCCAUUUGCCACCCGGCUUCAACGAGUACGACUUCGUGCCCGAGAGCUUCGACCGGGACAAAACCAUCGCCCUGAUCAUGAACAGUAGUGGCAGUACCGGAUUGCCCAAGGGCGUAGCCCUACCGCACCGCACCGCUUGUGUCCGAUUCAGUCAUGCCCGCGACCCCAUCUUCGGCAACCAGAUCAUCCCCGACACCGCUAUCCUCAGCGUGGUGCCAUUUCACCACGGCUUCGGCAUGUUCACCACGCUGGGCUACUUGAUCUGCGGCUUUCGGGUCGUGCUCAUGUACCGCUUCGAGGAGGAGCUAUUCUUGCGCAGCUUGCAAGACUAUAAGAUUCAAUCUGCCCUGCUGGUGCCCACACUAUUUAGCUUCUUCGCUAAGAGCACUCUCAUCGACAAGUACGACCUAAGCAACUUGCACGAGAUCGCCAGCGGCGGGGCGCCGCUCAGCAAGGAGGUAGGUGAGGCCGUGGCCAAACGCUUCCACCUACCAGGCAUCCGCCAGGGCUACGGCCUGACAGAAACAACCAGCGCCAUUCUGAUCACCCCCGAAGGGGACGACAAGCCUGGCGCAGUAGGCAAGGUGGUGCCCUUCUUCGAGGCUAAGGUGGUGGACUUGGACACCGGUAAGACACUGGGUGUGAACCAGCGCGGCGAGCUGUGCGUCCGUGGCCCCAUGAUCAUGAGCGGCUACGUUAACAACCCCGAGGCUACAAACGCUCUCAUCGACAAGGACGGCUGGCUGCACAGCGGCGACAUCGCCUACUGGGACGAGGACGAGCACUUCUUCAUCGUGGACCGGCUGAAGAGCCUGAUCAAAUACAAGGGCUACCAGGUAGCCCCAGCCGAACUGGAGAGCAUCCUGCUGCAACACCCCAACAUCUUCGACGCCGGGGUCGCCGGCCUGCCCGACGACGAUGCCGGCGAGCUGCCCGCCGCAGUCGUCGUGCUGGAACACGGUAAAACCAUGACCGAGAAGGAGAUCGUGGACUAUGUGGCCAGCCAGGUUACAACCGCCAAGAAGCUGCGCGGUGGUGUUGUGUUCGUGGACGAGGUGCCUAAAGGACUGACCGGCAAGUUGGACGCCCGCAAGAUCCGCGAGAUUCUCAUUAAGGCCAAGAAGGGCGGCAAGAUCGCCGUGUAA'
utr_upstream = 'GCAGCATCATGGAGGTTTGAAGATGCCGCATTTGGATTGGATGAATTCCAAATTCTGCTTGCTTGCTTTTTAATATTGATATGCTTATACACTTACACTTTATGCACAAAATGTAGGGTTATAATAATGTTAACATGGACATGATCTTCTTTATAATTCTACTTTGAGTGCTGTCTCCATGTTTGATGTATCTGAGCAGGTTGCTCCACAGGTAGCTCTAGGAGGGCTGGCAACTTAGAGGTGGGGAGCAGAGAATTCTCTTATCCAACATCAACATCTTGGTCAGATTTGAACTCTTCAATCTCTTGCACTCAAAGCTTGTTAAGATAGTTAAGCGTGCATAAGTTAACTTCCAATTTACATACTCTGCTTAGAATTTGGGGGAAAATTTAGAAATATAATTGACAGGATTATTGGAAATTTGTTATAATGAATGAAACATTTTGTCATATAAGATTCATATTTACTTCTTATACATTTGATAAAGTAAGGCATGGTTGTGGTTAATCTGGTTTATTTTTGT'
upstream = cds + utr_upstream
insert = 'CAGUGCUAGAGGAGGUCAGAAGAGGGCAUUGGAUCCCCCAGAACUGGAGUUAUACGGUAACCUCGUGGUGGUGCGCAGCCACCAUGUGGAUGGAUAUUGAGUUCCAAACACUGGUCCUGUGCAAGAGCAUCCAGUGCUCUUAAGUGCUGAGCCAUCUCUUUAGCUCC'
utr_downstream = 'TCCACAAGTTAAATAAATCATAAAACTTGA'
contact = upstream + insert + utr_downstream

print(len(upstream))
print(len(upstream) + len(insert) - 1)
print(contact[len(upstream)])
print(contact[len(upstream) + len(insert) - 1])
print(contact)

preprocess(cds, utr_upstream, insert, utr_downstream,name='b2m_site6', outpath='data.csv')


